/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/language` | `/language`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/setup` | `/setup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/companies` | `/companies`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/jobs` | `/jobs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/prep` | `/prep`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/language` | `/language`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/setup` | `/setup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/companies` | `/companies`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/jobs` | `/jobs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/prep` | `/prep`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/language${`?${string}` | `#${string}` | ''}` | `/language${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/setup${`?${string}` | `#${string}` | ''}` | `/setup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/companies${`?${string}` | `#${string}` | ''}` | `/companies${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/jobs${`?${string}` | `#${string}` | ''}` | `/jobs${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/prep${`?${string}` | `#${string}` | ''}` | `/prep${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/language` | `/language`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/setup` | `/setup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/companies` | `/companies`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/jobs` | `/jobs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/prep` | `/prep`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
